spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB  #单个文件的最大上限
      max-request-size: 1000MB #单个请求的文件总大小上限
  datasource:
    url: jdbc:mysql://82.157.48.184:3306/weibo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: weibo
    password: "a2dDDMNe5ZTdkddm"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    #邮箱配置
    protocol: smtp  #邮箱协议
    host: smtp.163.com #网易邮箱服务器地址
    username: rena2928992879@163.com  #发件人邮箱
    password: RDIYLOGCYHDKNXRU  #授权码
    default-encoding: UTF-8  #编码格式
    properties:
      mail:
        debug: true #打印日志

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/xml/*.xml
server:
  port: 8080